<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ESFE.Clothing_Store.UI</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ESFE. Clothing Store.DAL\ESFE. Clothing Store.DAL.csproj" />
    <ProjectReference Include="..\ESFE. Clothing Store.EN\ESFE. Clothing Store.EN.csproj" />
    <ProjectReference Include="..\ESFE. Clothing Store.LN\ESFE. Clothing Store.LN.csproj" />
  </ItemGroup>

</Project>